import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

import { useAccount } from "wagmi";
import { useAuthentication } from "~/contexts/Authentication";

const Home: NextPage = () => {
  const { address: addressWallet } = useAccount();

  const {
    isConnected,
    isConnecting,
    connectors,
    activeConnector,
    username,
    login,
    logout,
  } = useAuthentication();

  const { mutateAsync: testAddressPublic } =
    api.example.addressTestPublic.useMutation();

  const { mutateAsync: testAddressProtected } =
    api.example.addressTestProtected.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {addressWallet} | {isConnected ? "connected" : "NOT connected"}
        </div>
        {isConnected && (
          <div>
            Connected to {activeConnector?.name} as {username}
          </div>
        )}
        {connectors.map((connector) => (
          <button
            disabled={!connector.ready || !login || isConnecting}
            key={connector.id}
            // eslint-disable-next-line
            onClick={async () => {
              await login?.(connector);
            }}
          >
            {connector.name}
            {isConnecting && " (connecting)"}
          </button>
        ))}
        <br />
        <button
          disabled={!logout}
          // eslint-disable-next-line
          onClick={async () => {
            await logout?.();
          }}
        >
          disconnect
        </button>
        <br />
        <button
          // eslint-disable-next-line
          onClick={async () => {
            const addr = await testAddressPublic?.();
            console.log("ADDR public", addr);
          }}
        >
          test public
        </button>
        <br />
        <button
          // eslint-disable-next-line
          onClick={async () => {
            try {
              const addr = await testAddressProtected?.();
              console.log("ADDR protected", addr);
            } catch (e) {
              console.error(e);
            }
          }}
        >
          test protected
        </button>
        <br />
      </div>
    </>
  );
};

export default Home;
